#!/bin/bash
#proteinortho v. 6.2.3
#OrthoFinder version 2.2.6
#reference Spiralia proteomes (protein length >100 to match ORFs generated by TransDecoder) from Uniprot with BUSCO completeness > 90%(single AND duplicated)
#List of used proteomes:
#Apis_mellifera (Insecta, as outgroup)
#Homo_sapiens (as outgroup)
#Biomphalaria_glabrata (Mollusca, Spiralia)
#Crassostrea_gigas (Mollusca, Spiralia)
#Lottia_gigantea (Mollusca, Spiralia)
#Pomacea canaliculata (Mollusca, Spiralia)
#Capitella_teleta (Annelida, Spiralia)
#Dimorphilus_gyrociliatus (Annelida, Spiralia)
#Owenia_fusiformis (Annelida, Spiralia)

#excluded from analysis:
#Helobdella_robusta (excluded from analysis because of extremely high number of homeobox paralogous genes)
#Mytilus_edulis (excluded from analysis because of big proteome size and high computational demands)

orthofinder -f orthofinder_uniprot_gr100/
proteinortho -project=homeo_11 *.fasta
wait
echo 'Orthofinder and proteinortho analysis is done'

#summary for proteinortho generated by 
/mnt/c/phylo/programms/proteinortho/src/proteinortho_summary.pl homeo_11.blast-graph > graph_summary