#!/bin/bash
#identity threshold c=0.95 chosen based on Cd-Hit: a Fast Program for Clustering and Comparing Large Sets of Protein or Nucleotide Sequences for duplicate sequence removal
#Clustering Pdum contigs

workdir=./Good_contigs_CDHIT/

cd $workdir

# INPUT: #
FASTA=./Good_contigs/Pdum_new_ref.rnaSPAdes_and_Trinity.good.fasta
TAG=Pdum_new_ref.rnaSPAdes_and_Trinity.good.cdhit_c95

echo "***** CDHIT began to work with params: *****"
echo "FASTA: $FASTA"
echo "TAG: $TAG"
nohup ./miniconda3/envs/cdhit_env/bin/cd-hit-est -i $FASTA -o ${TAG}.fasta -c 0.95 -T 24 -d 0 -g 1 -r 1 -M 6000
wait
echo "##### Job is complete #####"
